language: node_js
node_js:
  - 0.8
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "npm install -g grunt-cli bower && bower install && grunt test-run"
